# Generated by Django 3.0.7 on 2020-08-24 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict_page', '0002_dictionaryc_dictionarye_dictionaryj_dictionaryjoint'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DictionaryJoint',
            new_name='DictionaryAll',
        ),
    ]
