# Generated by Django 3.0.7 on 2020-08-24 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dict_page', '0003_auto_20200824_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dictionaryall',
            old_name='japansese',
            new_name='japanese',
        ),
    ]
