# Generated by Django 3.1.1 on 2020-11-05 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_page', '0004_auto_20200824_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(blank=True, max_length=50, null=True)),
                ('def1', models.CharField(blank=True, max_length=1000, null=True)),
                ('def2', models.CharField(blank=True, max_length=1000, null=True)),
                ('def3', models.CharField(blank=True, max_length=1000, null=True)),
                ('def4', models.CharField(blank=True, max_length=1000, null=True)),
                ('def5', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DictionaryAll',
        ),
        migrations.DeleteModel(
            name='DictionaryC',
        ),
        migrations.DeleteModel(
            name='DictionaryE',
        ),
        migrations.DeleteModel(
            name='DictionaryJ',
        ),
    ]
