# Generated by Django 3.1.1 on 2021-03-25 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict_page', '0005_auto_20201105_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='def10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='def6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='def7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='def8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='dictionary',
            name='def9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
